defaults:
  - _self_
  - dataset: oboo
  - model: cnn

logdir: logs
device: cuda:0
seed: 42
checkpoint:
run_wandb: False

num_epochs: 1000
batch_size: 32
num_dataloaders: 2
grad_clip: 20
kl_weight: 10

train_data_ratio: 0.9
val_freq: 1
eval_freq: 10
save_freq: 50

optimizer:
  _target_: torch.optim.Adam
  lr: 3e-5

lr_scheduler:
  _target_: torch.optim.lr_scheduler.LinearLR
  start_factor: 1.0
  end_factor: 0.1


wandb:
  project: aloha
  entity: imgeorgiev
  group: