_target_: dataset.TrajectoryDataset
_recursive_: False
name: oboo
directory: /coc/flash7/datasets/egoplay/_OBOO_ROBOT/oboov2_robot_apr16/rawAloha
traj_len: 100
use_full_trajectory: True
downsample: 10
transforms:
- _target_: torchvision.transforms.v2.Normalize
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]