_target_: models.ACT
num_img: 2 # TODO shouldn't be hardcoded
qpos_dim: ???
act_len: ???
hidden_dim: 512
backbone:
  _target_: torchvision.models.resnet18
  weights: "DEFAULT"
transformer:
  _target_: models.Transformer
  d: ${model.hidden_dim}
  h: 8
  d_ff: 2048
  num_layers: 6
  dropout: 0.1
  default_pos_encoding: False